# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: OpenTK
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  The Open Toolkit library is set of fast, low-level C# bindings for OpenGL,
  OpenGL ES and OpenAL. It runs on all major platforms and powers hundreds of
  apps, games and scientific research.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  opentk

# Build settings
markdown: kramdown
