apiRules:
- exclude: 
    uidRegex: ^OpenTK\.Graphics\.ES11
- exclude: 
    uidRegex: ^OpenTK\.Graphics\.ES20
- exclude: 
    uidRegex: ^OpenTK\.Graphics\.ES30
- exclude: 
    uidRegex: ^OpenTK\.Graphics\.GL
- exclude: 
    uidRegex: ^OpenTK\.Graphics\.OpenGL
- exclude: 
    uidRegex: ^OpenTK\.Graphics\.OpenGL4
